### PR TITLE
newBlogPost method is complete

### PR DESCRIPTION
**Pull request by misko9251**
When a user creates a new post/blog, the author is autopopulated with the user objectid and then the postid gets pushed to the user document

### CODE REVIEW

**Comment by misko9251** [comment]
https://user-images.githubusercontent.com/101610922/208012511-a1ec0b2a-050e-4ead-b183-d8f432953bdc.mp4

Users can now like posts similarly to Instagram. Each post can only be liked once. If a post is unliked, the heart shows as regular/empty. If a post is liked, the heart shows as solid/filled. This toggles based on whether the logged in users DB document contains the blogs objectId in the "likes" property.

When a user clicks on a heart, two things happen: 
1) the blog objectId is saved as a value and placed in the likes array of the user object
2) the user objectId is saved as a value and placed in the likedBy array of the blog object

If the blog is already liked and the heart is clicked, the objectIds mentioned above are removed from their respective arrays

**Comment by misko9251** [comment]
Close #143 


https://user-images.githubusercontent.com/101610922/208213817-3f413394-e9b4-4e98-ab37-094ca627eb8f.mp4

Similar to posts, users can bookmark specific posts/blogs and remove their bookmark if they wish. Proper router and controller were set up to achieve this

**Comment by misko9251** [comment]
Close #144 

https://user-images.githubusercontent.com/101610922/208224173-bc000b0e-78eb-4aa6-9af4-58a86bd143e6.mp4

Cloudinary and Multer packages have been installed to handle uploading of images. To handle images, the following 3 properties must be provided to the .env, with the values coming from cloudinary's website:

CLOUD_NAME= 
API_KEY= 
API_SECRET= 

postPreview.css still needs an overhaul, but for now it pulls in the image from the db as it should once properly re-designed.

**Review by LucasMERN — APPROVED** [review]
LGTM

**Pull request merged**
